# Generated by Django 4.2.6 on 2023-10-27 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_file_upload_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file_upload',
            new_name='file',
        ),
    ]
